### ISSUE TITLE
How to create a button for all stories?

### ISSUE THREAD

**Issue by rwieruch** [ccpu/storybook-addon-toolbar-actions#15]
Hi @ccpu , thanks for this add-on. Is it possible to define a toolbar button for every story in the preview.js file?

**Comment by ccpu** [comment]
Hi @rwieruch, I am not sure about preview.js, but you can use [decorators ](https://storybook.js.org/docs/react/writing-stories/decorators) to put all your toolbar buttons into a decorator, making them available across all stories.
