### ISSUE TITLE
Can't find tslib

### ISSUE THREAD

**Issue by mparpaillon** [ccpu/storybook-addon-toolbar-actions#5]
Hi,
Thanks for the great addon.

I'm trying to use it but I'm getting this error

> Module not found: Error: storybook-addon-toolbar-actions tried to access tslib, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

Am I missing something?

**Comment by ccpu** [comment]
hi @mparpaillon ,

Unfortunately i cant say why you are receiving this error, it could be version conflict, i have upgrade package to latest storybook version (6.2.9), could you please try the plugin (v 0.4.7) with latest story book version an see if its working.

if not could you please make me small repo to try it my self.

Thanks

**Comment by mparpaillon** [comment]
No I'm still getting the error sadly. It's ok, I don't think I need this addon right now. I've found another way
If I'm the only one getting this error maybe it's coming from my env, so maybe we can close the issue.

Thanks a lot for taking the time.

**Comment by ccpu** [comment]
Not a problem, closing the issue for now.
